print("‘ÿ»Î÷–")
dofile(GetInfo(67).."hook.mod")
dofile(GetInfo(67).."system.mod")
dofile(GetInfo(67).."misc.mod")
dofile(GetInfo(67).."check.mod")
dofile(GetInfo(67).."walk.mod")
dofile(GetInfo(67).."items.mod")
dofile(GetInfo(67).."status.mod")
dofile(GetInfo(67).."alias.mod")
dofile(GetInfo(67).."search.mod")
dofile(GetInfo(67).."npcs.ini")

dofile(GetInfo(67).."caxie.mod")
mushmapper.settags("")
mushmapper.setflylist(GetVariable("flylist"))
