include=function(str)
	dofile(GetInfo(67)..str)
end
print("‘ÿ»Î÷–")
include("walk.mod")
include("loadconfig.mod")
include("hook.mod")
include("system.mod")
include("misc.mod")
include("check.mod")
include("items.mod")
include("status.mod")
include("alias.mod")
include("search.mod")
include("npcs.ini")

include("caxie.mod")
mushmapper.settags("")
